site_name: Manual de uso del AGDe
theme:
  name: material
  palette: 'indigo'

nav:
  - Inicio: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: python:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - minify:
      minify_html: true
