site_name: Manual de uso
theme:
  name: material

# Extensiones de Markdown (agregar esto)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - footnotes
  - tables

# Plugins (agregar esto)
plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - minify:
      minify_html: true