site_name: Manual de uso del AGDe
theme:
  name: material
  palette: 'indigo'
  language: es
  features:
    - search.suggest
    - navigation.footer

nav:
  - Inicio: index.md
  - Acerca de: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: python:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: "#"

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/IDESPOUNA
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/idespo_una/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@idespouna1975

copyright: 'Copyright &copy; 2026 - <span id="current-year"></span> <script>document.getElementById("current-year").innerHTML = new Date().getFullYear();</script> Livan Gómez'